---
- name: BGP test
  hosts: IxNetRestApiServer

  tasks:
    - name: Configuring BGP NGPF
      bgpModule:
        apiServerIp: '192.168.70.3'
        apiServerIpPort: 11009
        osPlatform: 'windows'
        forceTakePortOwnership: True
        releasePortsWhenDone: False
        enableDebugTracing: True
        deleteSessionAfterTest: True
        ixChassisIp: '192.168.70.11'
        portList: [['192.168.70.11', '1', '1'], ['192.168.70.11', '2', '1']]
        linuxUsername: 'admin'
        linuxPassword: 'admin'
        configLicense: True
        licenseServerIp: '192.168.70.3'
        licenseMode: 'subscription'
        licenseTier: 'tier3'

        topologyGroup1Name: 'Topo1'
        topologyGroup1Ports: ['192.168.70.11', '1', '1']
        topologyGroup2Name: 'Topo2'
        topologyGroup2Ports: ['192.168.70.11', '2', '1']

        deviceGroup1Name: 'DG1'
        deviceGroup1Multiplier: 1
        deviceGroup2Name: 'DG2'
        deviceGroup2Multiplier: 1

        ethernet1Name: 'Eth1'
        ethernet1MacAddress: '00:01:01:01:00:01'
        ethernet1MacDirection: 'increment'
        ethernet1MacStep: '00:00:00:00:00:00'
        ethernet1MacPortStep: 'disabled'
        ethernet1VlanId: 103
        ethernet1VlanIdDirection: 'increment'
        ethernet1VlanIdStep: 0

        ethernet2Name: 'Eth2'
        ethernet2MacAddress: '00:01:02:01:00:01'
        ethernet2MacDirection: 'increment'
        ethernet2MacStep: '00:00:00:00:00:00'
        ethernet2MacPortStep: 'disabled'
        ethernet2VlanId: 103
        ethernet2VlanIdDirection: 'increment'
        ethernet2VlanIdStep: 0

        ipv41Address: '1.1.1.1'
        ipv41AddressDirection: 'increment'
        ipv41AddressStep: '0.0.0.1'
        ipv41AddressPortStep: 'disabled'
        ipv41Gateway: '1.1.1.2'
        ipv41GatewayDirection: 'increment'
        ipv41GatewayStep: '0.0.0.0'
        ipv41GatewayPortStep: 'disabled'
        ipv41AddressPrefix: 24
        ipv41ResolveGateway: True

        ipv42Address: '1.1.1.2'
        ipv42AddressDirection: 'increment'
        ipv42AddressStep: '0.0.0.1'
        ipv42AddressPortStep: 'disabled'
        ipv42Gateway: '1.1.1.1'
        ipv42GatewayDirection: 'increment'
        ipv42GatewayStep: '0.0.0.0'
        ipv42GatewayPortStep: 'disabled'
        ipv42AddressPrefix: 24
        ipv42ResolveGateway: True
        
        bgp1Name: 'bgp_1'
        bgp1Enable: True
        bgp1HoldTimer: 90
        bgp1DutIp: '1.1.1.2'
        bgp1DutIpDirection: 'increment'
        bgp1DutIpStep: '0.0.0.0'
        bgp1LocalAsBytes: 101
        bgp1EnableGracefulRestart: False
        bgp1RestartTime: 45
        bgp1Type: 'internal'

        bgp2Name: 'bgp_2'
        bgp2Enable: True
        bgp2HoldTimer: 90
        bgp2DutIp: '1.1.1.1'
        bgp2DutIpDirection: 'increment'
        bgp2DutIpStep: '0.0.0.0'
        bgp2LocalAsBytes: 101
        bgp2EnableGracefulRestart: False
        bgp2RestartTime: 45
        bgp2Type: 'internal'

        networkGroup1Name: 'NetworkGroup1'
        networkGroup1Multiplier: 100
        networkGroup1Address: '160.1.0.0'
        networkGroup1AddressStep: '0.0.0.1'
        networkGroup1AddressDirection: 'increment'
        networkGroup1PrefixLength: 32

        networkGroup2Name: 'NetworkGroup2'
        networkGroup2Multiplier: 100
        networkGroup2Address: '180.1.0.0'
        networkGroup2AddressStep: '0.0.0.1'
        networkGroup2AddressDirection: 'increment'
        networkGroup2PrefixLength: 32

        trafficItemName: 'Top1 to Topo2'
        trafficItemType: 'ipv4'
        trafficItemBiDirection: True
        trafficItemSrcDestMesh: one-to-one
        trafficItemRouteMesh: oneToOne
        trafficItemAllowSelfDestined: False
        trafficItemTrackBy: ['flowGroup0', 'vlanVlanId0']
        endpointName: 'Flow-Group-1'
        transmissionType: 'fixedFrameCount'
        frameCount: 50000
        frameRate: 88
        frameRateType: 'percentLineRate'
        frameSize: 128

#      register: out
#    - debug: var=out





