from ixnetwork_restpy.base import Base
from ixnetwork_restpy.files import Files


class Igmp(Base):
	"""The Igmp class encapsulates a required igmp node in the ixnetwork hierarchy.

	An instance of the class can be obtained by accessing the Igmp property from a parent instance.
	The internal properties list will contain one and only one set of properties which is populated when the property is accessed.
	"""

	_SDM_NAME = 'igmp'

	def __init__(self, parent):
		super(Igmp, self).__init__(parent)

	@property
	def Host(self):
		"""An instance of the Host class.

		Returns:
			obj(ixnetwork_restpy.testplatform.sessions.ixnetwork.vport.protocols.igmp.host.host.Host)

		Raises:
			NotFoundError: The requested resource does not exist on the server
			ServerError: The server has encountered an uncategorized error condition
		"""
		from ixnetwork_restpy.testplatform.sessions.ixnetwork.vport.protocols.igmp.host.host import Host
		return Host(self)

	@property
	def Querier(self):
		"""An instance of the Querier class.

		Returns:
			obj(ixnetwork_restpy.testplatform.sessions.ixnetwork.vport.protocols.igmp.querier.querier.Querier)

		Raises:
			NotFoundError: The requested resource does not exist on the server
			ServerError: The server has encountered an uncategorized error condition
		"""
		from ixnetwork_restpy.testplatform.sessions.ixnetwork.vport.protocols.igmp.querier.querier import Querier
		return Querier(self)

	@property
	def Enabled(self):
		"""Enables or disables the use of this emulated EIGRP router in the emulated EIGRP network. (default = disabled)

		Returns:
			bool
		"""
		return self._get_attribute('enabled')
	@Enabled.setter
	def Enabled(self, value):
		self._set_attribute('enabled', value)

	@property
	def NumberOfGroups(self):
		"""Provides a means of throttling the amount of IGMP traffic generated by the port.

		Returns:
			number
		"""
		return self._get_attribute('numberOfGroups')
	@NumberOfGroups.setter
	def NumberOfGroups(self, value):
		self._set_attribute('numberOfGroups', value)

	@property
	def NumberOfQueries(self):
		"""Provides a means of throttling the amount of IGMP queries generated by the port.

		Returns:
			number
		"""
		return self._get_attribute('numberOfQueries')
	@NumberOfQueries.setter
	def NumberOfQueries(self, value):
		self._set_attribute('numberOfQueries', value)

	@property
	def QueryTimePeriod(self):
		"""The time, in milliseconds, between queries.

		Returns:
			number
		"""
		return self._get_attribute('queryTimePeriod')
	@QueryTimePeriod.setter
	def QueryTimePeriod(self, value):
		self._set_attribute('queryTimePeriod', value)

	@property
	def RunningState(self):
		"""The current running state of the IGMP server.

		Returns:
			str(unknown|stopped|stopping|starting|started)
		"""
		return self._get_attribute('runningState')

	@property
	def SendLeaveOnHostDisable(self):
		"""Send Leave On Host Disable

		Returns:
			bool
		"""
		return self._get_attribute('sendLeaveOnHostDisable')
	@SendLeaveOnHostDisable.setter
	def SendLeaveOnHostDisable(self, value):
		self._set_attribute('sendLeaveOnHostDisable', value)

	@property
	def SendLeaveOnStop(self):
		"""Send leaves on stop (v2 and v3 only).

		Returns:
			bool
		"""
		return self._get_attribute('sendLeaveOnStop')
	@SendLeaveOnStop.setter
	def SendLeaveOnStop(self, value):
		self._set_attribute('sendLeaveOnStop', value)

	@property
	def StatsEnabled(self):
		"""If true, this object enables the IGMP statistics.

		Returns:
			bool
		"""
		return self._get_attribute('statsEnabled')
	@StatsEnabled.setter
	def StatsEnabled(self, value):
		self._set_attribute('statsEnabled', value)

	@property
	def TimePeriod(self):
		"""Specifies the length of each time period during which the specified number of IGMP groups will be advertised.

		Returns:
			number
		"""
		return self._get_attribute('timePeriod')
	@TimePeriod.setter
	def TimePeriod(self, value):
		self._set_attribute('timePeriod', value)

	def Join(self, Arg2, Arg3):
		"""Executes the join operation on the server.

		NOT DEFINED

		Args:
			Arg1 (str(None|/api/v1/sessions/1/ixnetwork/vport?deepchild=igmp)): The method internally set Arg1 to the current href for this instance
			Arg2 (str): NOT DEFINED
			Arg3 (number): NOT DEFINED

		Raises:
			NotFoundError: The requested resource does not exist on the server
			ServerError: The server has encountered an uncategorized error condition
		"""
		Arg1 = self.href
		return self._execute('Join', payload=locals(), response_object=None)

	def Leave(self, Arg2, Arg3):
		"""Executes the leave operation on the server.

		NOT DEFINED

		Args:
			Arg1 (str(None|/api/v1/sessions/1/ixnetwork/vport?deepchild=igmp)): The method internally set Arg1 to the current href for this instance
			Arg2 (str): NOT DEFINED
			Arg3 (number): NOT DEFINED

		Raises:
			NotFoundError: The requested resource does not exist on the server
			ServerError: The server has encountered an uncategorized error condition
		"""
		Arg1 = self.href
		return self._execute('Leave', payload=locals(), response_object=None)

	def Start(self):
		"""Executes the start operation on the server.

		Starts the EIGRP protocol on a port or group of ports simultaneously.

		Args:
			Arg1 (str(None|/api/v1/sessions/1/ixnetwork/vport?deepchild=igmp)): The method internally set Arg1 to the current href for this instance

		Raises:
			NotFoundError: The requested resource does not exist on the server
			ServerError: The server has encountered an uncategorized error condition
		"""
		Arg1 = self.href
		return self._execute('Start', payload=locals(), response_object=None)

	def Stop(self):
		"""Executes the stop operation on the server.

		Stops the IGMP protocol on a port or group of ports simultaneously.

		Args:
			Arg1 (str(None|/api/v1/sessions/1/ixnetwork/vport?deepchild=igmp)): The method internally set Arg1 to the current href for this instance

		Raises:
			NotFoundError: The requested resource does not exist on the server
			ServerError: The server has encountered an uncategorized error condition
		"""
		Arg1 = self.href
		return self._execute('Stop', payload=locals(), response_object=None)
